### ISSUE TITLE
macOS无法打开

### ISSUE THREAD

**Issue by OpenJarvisAI** [shaonhuang/V2rayX#12]
<img width="372" alt="image" src="https://github.com/shaonhuang/V2rayX/assets/136460643/78109631-e9f3-4731-8399-db5a66d2cc02">

**Comment by shaonhuang** [comment]
The reason why it appears so is that I skipped signing it.

Please execute follow command.
`sudo xattr -r -d com.apple.quarantine /Applications/V2rayX.app`
